services:
#  postgres:
#    image: postgres:16
#    container_name: scheduler_postgres
#    environment:
#      POSTGRES_USER: scheduling
#      POSTGRES_PASSWORD: scheduling
#      POSTGRES_DB: scheduling
#    ports:
#      - "5433:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#      - ../data:/data
#    command:
#      - "postgres"
#      - "-c"
#      - "shared_buffers=512MB"
#      - "-c"
#      - "work_mem=32MB"
#      - "-c"
#      - "maintenance_work_mem=256MB"
#      - "-c"
#      - "effective_cache_size=2GB"

  mongo:
    image: mongo:latest
    container_name: scheduler_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: scheduling
      MONGO_INITDB_ROOT_PASSWORD: scheduling
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  prometheus:
    image: prom/prometheus:latest
    container_name: scheduler_prometheus
    ports:
      - "9095:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

volumes:
  postgres_data:
  mongo_data: